export const FETCH_HOME_DETAIL_REQUEST = 'FETCH_HOME_DETAIL_REQUEST';
export const FETCH_HOME_DETAIL_REQUEST_SUCCESS = 'FETCH_HOME_DETAIL_REQUEST_SUCCESS';
export const FETCH_HOME_DETAIL_REQUEST_FAILURE = 'FETCH_HOME_DETAIL_REQUEST_FAILURE';
