export const ORDER_REQUEST_CREATE = 'ORDER_REQUEST_CREATE';
export const ORDER_REQUEST_FETCH = 'ORDER_REQUEST_FETCH';
export const ORDER_REQUEST_SUCCESS = 'ORDER_REQUEST_SUCCESS';
export const ORDER_REQUEST_FAILURE = 'ORDER_REQUEST_FAILURE';
