export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCTS_REQUEST_SUCCESS = "FETCH_PRODUCTS_REQUEST_SUCCESS";
export const FETCH_PRODUCTS_REQUEST_FAILURE = "FETCH_PRODUCTS_REQUEST_FAILURE";

export const FETCH_PRODUCT_REQUEST = "FETCH_PRODUCT_REQUEST";
export const FETCH_PRODUCT_REQUEST_SUCCESS = "FETCH_PRODUCT_REQUEST_SUCCESS";
export const FETCH_PRODUCT_REQUEST_FAILURE = "FETCH_PRODUCT_REQUEST_FAILURE";

export const FETCH_RELATED_PRODUCTS_REQUEST = "FETCH_RELATED_PRODUCT_REQUEST";
export const FETCH_RELATED_PRODUCTS_REQUEST_SUCCESS = "FETCH_RELATED_PRODUCT_REQUEST_SUCCESS";
export const FETCH_RELATED_PRODUCTS_REQUEST_FAILURE = "FETCH_RELATED_PRODUCT_REQUEST_FAILURE";

export const UPDATE_PRODUCT_DATA = "UPDATE_PRODUCT_DATA";
