export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_REQUEST_SUCCESS = 'FETCH_PRODUCTS_REQUEST_SUCCESS';
export const FETCH_PRODUCTS_REQUEST_FAILURE = 'FETCH_PRODUCTS_REQUEST_FAILURE';
